def serialize_record(message_class, field_name_mapping, record_data):
    """Serialize a record into a protobuf message.

    Args:
        message_class: The protobuf message class generated by the builder
        field_name_mapping: Dictionary mapping from original field names to protobuf field names
        record_data: Dictionary containing data to serialize with field names as keys

    Returns:
        bytes: Serialized protobuf message
    """
    msg = message_class()

    for field_name, value in record_data.items():
        if field_name in field_name_mapping:
            proto_field_name = field_name_mapping[field_name]
            setattr(msg, proto_field_name, value)

    return msg.SerializeToString()
